# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercice_applicatif.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_num_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_etudiant.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.lineEdit_num_etudiant.setObjectName("lineEdit_num_etudiant")
        self.label_num_etudiant = QtWidgets.QLabel(self.centralwidget)
        self.label_num_etudiant.setGeometry(QtCore.QRect(30, 40, 91, 16))
        self.label_num_etudiant.setObjectName("label_num_etudiant")
        self.lineEdit_nom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nom.setGeometry(QtCore.QRect(60, 70, 113, 20))
        self.lineEdit_nom.setObjectName("lineEdit_nom")
        self.label_nom = QtWidgets.QLabel(self.centralwidget)
        self.label_nom.setGeometry(QtCore.QRect(30, 70, 47, 13))
        self.label_nom.setObjectName("label_nom")
        self.lineEdit_prenom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_prenom.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.lineEdit_prenom.setObjectName("lineEdit_prenom")
        self.label_prenom = QtWidgets.QLabel(self.centralwidget)
        self.label_prenom.setGeometry(QtCore.QRect(30, 100, 47, 13))
        self.label_prenom.setObjectName("label_prenom")
        self.lineEdit_programme = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_programme.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.lineEdit_programme.setObjectName("lineEdit_programme")
        self.label_programme = QtWidgets.QLabel(self.centralwidget)
        self.label_programme.setGeometry(QtCore.QRect(30, 130, 61, 16))
        self.label_programme.setObjectName("label_programme")
        self.pushButton_creer_objet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_creer_objet.setGeometry(QtCore.QRect(90, 170, 75, 23))
        self.pushButton_creer_objet.setObjectName("pushButton_creer_objet")
        self.label_affichage = QtWidgets.QLabel(self.centralwidget)
        self.label_affichage.setGeometry(QtCore.QRect(280, 40, 261, 151))
        self.label_affichage.setText("")
        self.label_affichage.setObjectName("label_affichage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_num_etudiant.setText(_translate("MainWindow", "Numéro étudiant:"))
        self.label_nom.setText(_translate("MainWindow", "Nom:"))
        self.label_prenom.setText(_translate("MainWindow", "Prénom:"))
        self.label_programme.setText(_translate("MainWindow", "Programme:"))
        self.pushButton_creer_objet.setText(_translate("MainWindow", "Creer"))
