# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mon_interface_graphique.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 1808)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_nom_etudiant = QtWidgets.QLabel(self.centralwidget)
        self.label_nom_etudiant.setGeometry(QtCore.QRect(80, 50, 91, 16))
        self.label_nom_etudiant.setObjectName("label_nom_etudiant")
        self.lineEdit_nom_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nom_etudiant.setGeometry(QtCore.QRect(70, 70, 113, 20))
        self.lineEdit_nom_etudiant.setText("")
        self.lineEdit_nom_etudiant.setObjectName("lineEdit_nom_etudiant")
        self.pushButton_Valider = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Valider.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.pushButton_Valider.setObjectName("pushButton_Valider")
        self.label_message = QtWidgets.QLabel(self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(70, 140, 131, 20))
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_nom_etudiant.setText(_translate("MainWindow", "Nom de l\'étudiant"))
        self.pushButton_Valider.setText(_translate("MainWindow", "Valider"))
