# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boite_associer_cours.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(285, 465)
        self.label_etudiant = QtWidgets.QLabel(Dialog)
        self.label_etudiant.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_etudiant.setFont(font)
        self.label_etudiant.setObjectName("label_etudiant")
        self.comboBox_etudiant = QtWidgets.QComboBox(Dialog)
        self.comboBox_etudiant.setGeometry(QtCore.QRect(10, 30, 81, 22))
        self.comboBox_etudiant.setObjectName("comboBox_etudiant")
        self.label_cours = QtWidgets.QLabel(Dialog)
        self.label_cours.setGeometry(QtCore.QRect(10, 70, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cours.setFont(font)
        self.label_cours.setObjectName("label_cours")
        self.comboBox_cours = QtWidgets.QComboBox(Dialog)
        self.comboBox_cours.setGeometry(QtCore.QRect(10, 90, 81, 22))
        self.comboBox_cours.setObjectName("comboBox_cours")
        self.pushButton_ajouter = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter.setGeometry(QtCore.QRect(100, 90, 21, 23))
        self.pushButton_ajouter.setObjectName("pushButton_ajouter")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(10, 150, 231, 181))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 340, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_etudiant.setText(_translate("Dialog", "Étudiant"))
        self.label_cours.setText(_translate("Dialog", "Cours"))
        self.pushButton_ajouter.setText(_translate("Dialog", "+"))
        self.label.setText(_translate("Dialog", "Liste des cours"))
        self.pushButton.setText(_translate("Dialog", "Associer"))
