# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boite_dialogue_Ajouter_cours.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_boiteDialog_cours(object):
    def setupUi(self, boiteDialog_cours):
        boiteDialog_cours.setObjectName("boiteDialog_cours")
        boiteDialog_cours.resize(400, 300)
        self.label_sigle_cours = QtWidgets.QLabel(boiteDialog_cours)
        self.label_sigle_cours.setGeometry(QtCore.QRect(30, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sigle_cours.setFont(font)
        self.label_sigle_cours.setObjectName("label_sigle_cours")
        self.label_nom_cours = QtWidgets.QLabel(boiteDialog_cours)
        self.label_nom_cours.setGeometry(QtCore.QRect(30, 80, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nom_cours.setFont(font)
        self.label_nom_cours.setObjectName("label_nom_cours")
        self.label_nb_heures = QtWidgets.QLabel(boiteDialog_cours)
        self.label_nb_heures.setGeometry(QtCore.QRect(30, 140, 131, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nb_heures.setFont(font)
        self.label_nb_heures.setObjectName("label_nb_heures")
        self.pushButton_Ajouter = QtWidgets.QPushButton(boiteDialog_cours)
        self.pushButton_Ajouter.setGeometry(QtCore.QRect(30, 200, 91, 31))
        self.pushButton_Ajouter.setObjectName("pushButton_Ajouter")
        self.textBrowser = QtWidgets.QTextBrowser(boiteDialog_cours)
        self.textBrowser.setGeometry(QtCore.QRect(170, 20, 211, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_sigle = QtWidgets.QLineEdit(boiteDialog_cours)
        self.lineEdit_sigle.setGeometry(QtCore.QRect(30, 40, 113, 31))
        self.lineEdit_sigle.setObjectName("lineEdit_sigle")
        self.lineEdit_nom = QtWidgets.QLineEdit(boiteDialog_cours)
        self.lineEdit_nom.setGeometry(QtCore.QRect(30, 100, 113, 31))
        self.lineEdit_nom.setObjectName("lineEdit_nom")
        self.lineEdit_nb_heures = QtWidgets.QLineEdit(boiteDialog_cours)
        self.lineEdit_nb_heures.setGeometry(QtCore.QRect(30, 160, 113, 31))
        self.lineEdit_nb_heures.setObjectName("lineEdit_nb_heures")
        self.label_message_erreur = QtWidgets.QLabel(boiteDialog_cours)
        self.label_message_erreur.setGeometry(QtCore.QRect(170, 200, 211, 16))
        self.label_message_erreur.setText("")
        self.label_message_erreur.setObjectName("label_message_erreur")

        self.retranslateUi(boiteDialog_cours)
        QtCore.QMetaObject.connectSlotsByName(boiteDialog_cours)

    def retranslateUi(self, boiteDialog_cours):
        _translate = QtCore.QCoreApplication.translate
        boiteDialog_cours.setWindowTitle(_translate("boiteDialog_cours", "Dialog"))
        self.label_sigle_cours.setText(_translate("boiteDialog_cours", "Sigle du cours"))
        self.label_nom_cours.setText(_translate("boiteDialog_cours", "Nom du cours"))
        self.label_nb_heures.setText(_translate("boiteDialog_cours", "Nombre d\'heures"))
        self.pushButton_Ajouter.setText(_translate("boiteDialog_cours", "Ajouter"))
