# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listview_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(20, 40, 256, 192))
        self.listView.setObjectName("listView")
        self.label_ls_etudiants = QtWidgets.QLabel(Dialog)
        self.label_ls_etudiants.setGeometry(QtCore.QRect(20, 20, 291, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_ls_etudiants.setFont(font)
        self.label_ls_etudiants.setObjectName("label_ls_etudiants")
        self.pushButton_Quitter = QtWidgets.QPushButton(Dialog)
        self.pushButton_Quitter.setGeometry(QtCore.QRect(20, 240, 101, 41))
        self.pushButton_Quitter.setObjectName("pushButton_Quitter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_ls_etudiants.setText(_translate("Dialog", "Liste des étudiants/étudiantes"))
        self.pushButton_Quitter.setText(_translate("Dialog", "Quitter"))
