# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogRecherche.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(866, 475)
        self.label_nom_fournisseur = QtWidgets.QLabel(Dialog)
        self.label_nom_fournisseur.setGeometry(QtCore.QRect(40, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nom_fournisseur.setFont(font)
        self.label_nom_fournisseur.setObjectName("label_nom_fournisseur")
        self.comboBox_nom_fournisseur = QtWidgets.QComboBox(Dialog)
        self.comboBox_nom_fournisseur.setGeometry(QtCore.QRect(40, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_nom_fournisseur.setFont(font)
        self.comboBox_nom_fournisseur.setObjectName("comboBox_nom_fournisseur")
        self.comboBox_nom_fournisseur.addItem("")
        self.comboBox_nom_fournisseur.addItem("")
        self.comboBox_nom_fournisseur.addItem("")
        self.comboBox_nom_fournisseur.addItem("")
        self.comboBox_nom_fournisseur.addItem("")
        self.pushButton_afficher = QtWidgets.QPushButton(Dialog)
        self.pushButton_afficher.setGeometry(QtCore.QRect(320, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_afficher.setFont(font)
        self.pushButton_afficher.setObjectName("pushButton_afficher")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 140, 581, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(40, 160, 541, 271))
        self.listView.setObjectName("listView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_nom_fournisseur.setText(_translate("Dialog", "Nom fournisseur"))
        self.comboBox_nom_fournisseur.setItemText(0, _translate("Dialog", "Jean Coutu"))
        self.comboBox_nom_fournisseur.setItemText(1, _translate("Dialog", "Uniprix"))
        self.comboBox_nom_fournisseur.setItemText(2, _translate("Dialog", "Shoppers Drug Mart"))
        self.comboBox_nom_fournisseur.setItemText(3, _translate("Dialog", "Familiprix"))
        self.comboBox_nom_fournisseur.setItemText(4, _translate("Dialog", "Pharmaprix"))
        self.pushButton_afficher.setText(_translate("Dialog", "Afficher"))
        self.label.setText(_translate("Dialog", "Listview affichant la liste des patients qui achètent des médicaments du fournisseur via la pharmacie"))
