# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_fournisseur.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(811, 421)
        self.label_code_fournisseur = QtWidgets.QLabel(Dialog)
        self.label_code_fournisseur.setGeometry(QtCore.QRect(30, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_code_fournisseur.setFont(font)
        self.label_code_fournisseur.setObjectName("label_code_fournisseur")
        self.lineEdit_code_fournisseur = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_code_fournisseur.setGeometry(QtCore.QRect(30, 40, 141, 31))
        self.lineEdit_code_fournisseur.setObjectName("lineEdit_code_fournisseur")
        self.labelErreur_code_fournisseur = QtWidgets.QLabel(Dialog)
        self.labelErreur_code_fournisseur.setGeometry(QtCore.QRect(30, 80, 291, 16))
        self.labelErreur_code_fournisseur.setObjectName("labelErreur_code_fournisseur")
        self.label_nom_compagnie = QtWidgets.QLabel(Dialog)
        self.label_nom_compagnie.setGeometry(QtCore.QRect(30, 120, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nom_compagnie.setFont(font)
        self.label_nom_compagnie.setObjectName("label_nom_compagnie")
        self.lineEdit_nom_compagnie = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nom_compagnie.setGeometry(QtCore.QRect(30, 140, 151, 31))
        self.lineEdit_nom_compagnie.setObjectName("lineEdit_nom_compagnie")
        self.labelErreur_nom_compagnie = QtWidgets.QLabel(Dialog)
        self.labelErreur_nom_compagnie.setGeometry(QtCore.QRect(30, 180, 291, 16))
        self.labelErreur_nom_compagnie.setObjectName("labelErreur_nom_compagnie")
        self.label_patient = QtWidgets.QLabel(Dialog)
        self.label_patient.setGeometry(QtCore.QRect(360, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_patient.setFont(font)
        self.label_patient.setObjectName("label_patient")
        self.comboBox_patient = QtWidgets.QComboBox(Dialog)
        self.comboBox_patient.setGeometry(QtCore.QRect(360, 40, 141, 31))
        self.comboBox_patient.setObjectName("comboBox_patient")
        self.pushButton_ajouter_listview = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter_listview.setGeometry(QtCore.QRect(360, 100, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_ajouter_listview.setFont(font)
        self.pushButton_ajouter_listview.setObjectName("pushButton_ajouter_listview")
        self.label_list_view = QtWidgets.QLabel(Dialog)
        self.label_list_view.setGeometry(QtCore.QRect(360, 160, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_list_view.setFont(font)
        self.label_list_view.setObjectName("label_list_view")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(360, 190, 431, 171))
        self.listView.setObjectName("listView")
        self.pushButton_serialiser = QtWidgets.QPushButton(Dialog)
        self.pushButton_serialiser.setGeometry(QtCore.QRect(150, 260, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_serialiser.setFont(font)
        self.pushButton_serialiser.setObjectName("pushButton_serialiser")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 320, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_code_fournisseur.setText(_translate("Dialog", "Code du fournisseur"))
        self.labelErreur_code_fournisseur.setText(_translate("Dialog", "Entrer la lettre F suivie de cinq caractères alphanumériques"))
        self.label_nom_compagnie.setText(_translate("Dialog", "Nom de la compagnie"))
        self.labelErreur_nom_compagnie.setText(_translate("Dialog", "Alphanumérique de lomgueur inférieur à 30"))
        self.label_patient.setText(_translate("Dialog", "Patient"))
        self.pushButton_ajouter_listview.setText(_translate("Dialog", "Ajouter le patient à la listview"))
        self.label_list_view.setText(_translate("Dialog", "La listview qui contient la liste des patients qui achètent les médicaments de ce fournisseur"))
        self.pushButton_serialiser.setText(_translate("Dialog", "Sérialiser fournisseur"))
        self.pushButton.setText(_translate("Dialog", "Désérialiser fournisseur"))
