# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_pharmacie.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_bienvenue = QtWidgets.QLabel(self.centralwidget)
        self.label_bienvenue.setGeometry(QtCore.QRect(180, 60, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_bienvenue.setFont(font)
        self.label_bienvenue.setObjectName("label_bienvenue")
        self.pushButton_patient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_patient.setGeometry(QtCore.QRect(200, 130, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_patient.setFont(font)
        self.pushButton_patient.setObjectName("pushButton_patient")
        self.pushButton_medicament = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_medicament.setGeometry(QtCore.QRect(420, 130, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_medicament.setFont(font)
        self.pushButton_medicament.setObjectName("pushButton_medicament")
        self.pushButton_fournisseur = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fournisseur.setGeometry(QtCore.QRect(200, 220, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_fournisseur.setFont(font)
        self.pushButton_fournisseur.setObjectName("pushButton_fournisseur")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 220, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_bienvenue.setText(_translate("MainWindow", "Bienvenue à la pharmacie Healthcare !"))
        self.pushButton_patient.setText(_translate("MainWindow", "Patient"))
        self.pushButton_medicament.setText(_translate("MainWindow", "Médicament"))
        self.pushButton_fournisseur.setText(_translate("MainWindow", "Fournisseur"))
        self.pushButton.setText(_translate("MainWindow", "Rechercher"))
